services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: authDB
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  initdb:
    image: initdb
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_USER: my_pgadmin_user
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_DEFAULT_SERVER: db
      PGADMIN_DEFAULT_SERVER_PORT: 5432
      PGADMIN_DEFAULT_SERVER_DATABASE: authDB
      PGADMIN_DEFAULT_SERVER_USERNAME: user
      PGADMIN_DEFAULT_EMAIL: v@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db