services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: authDB
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  
  # initdb:
  #   image:
  #     build:
  #       context: .
  #       dockerfile: Dockerfile
  #   depends_on:
  #     - db

